fix

diff --git a/.github/workflows/dotnet-desktop.yml b/.github/workflows/dotnet-desktop.yml
--- a/.github/workflows/dotnet-desktop.yml
+++ b/.github/workflows/dotnet-desktop.yml
@@ -50,30 +50,32 @@ jobs:
     - name: Zip EasyBrailleEdit
       shell: pwsh
       run: |
-        $appName = "EasyBrailleEdit"
-        $sourFolder = "$(Resolve-Path ./publish/$appName)"
-        $zipPath = ".\publish\$appName-v${{ steps.get_version.outputs.VERSION }}.zip"
+        $sourFolder = "$(Resolve-Path ./publish/EasyBrailleEdit)"
+        $zipPath = ".\publish\EasyBrailleEdit-v${{ steps.get_version.outputs.VERSION }}.zip"
         Write-Host "Compressing $sourceFolder\*  to  $zipPath"
         Compress-Archive -Path "$sourceFolder\*" -DestinationPath $zipPath -Force
-        # Debug current directory and files
-        #Write-Host "Current directory: $pwd"
-        #Write-Host "Files in publish directory:"
-        #Get-ChildItem -Path .\publish | ForEach-Object { $_.FullName }      
-        #if (Test-Path $zipPath) {
-        #  Write-Host "✅ Zip created at: $zipPath"
-        #} else {
-        #  Write-Error "❌ Zip file not found at: $zipPath"
-        #  exit 1
-        #}
+        # Ensure the zip file is created.
+        if (Test-Path $zipPath) {
+          Write-Host "✅ Zip created at: $zipPath"
+        } else {
+          Write-Error "❌ Zip file not found at: $zipPath"
+          exit 1
+        }
       
     - name: Zip Txt2Brl      
       shell: pwsh
       run: |
-        $appName = "Txt2Brl"
-        $sourFolder = "$(Resolve-Path ./publish/$appName"
-        $zipPath = ".\publish\$appName-v${{ steps.get_version.outputs.VERSION }}.zip"
+        $sourFolder = "$(Resolve-Path ./publish/Txt2Brl"
+        $zipPath = ".\publish\Txt2Brl-v${{ steps.get_version.outputs.VERSION }}.zip"
         Write-Host "Compressing $sourceFolder\*  to  $zipPath"
-        Compress-Archive -Path .\publish\Txt2Brl\* -DestinationPath .\publish\Txt2Brl-v${{ steps.get_version.outputs.VERSION }}.zip      
+        Compress-Archive -Path .\publish\Txt2Brl\* -DestinationPath $zipPath -Force      
+        # Ensure the zip file is created.
+        if (Test-Path $zipPath) {
+          Write-Host "✅ Zip created at: $zipPath"
+        } else {
+          Write-Error "❌ Zip file not found at: $zipPath"
+          exit 1
+        }
       
     - name: Upload EasyBrailleEdit artifacts
       uses: actions/upload-artifact@v4
